config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  resource :registration
  resource :session
  resource :password_reset
  resource :password
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  normalizes :email, with: ->(email) { email.strip.downcase }

  generates_token_for :password_reset, expires_in: 15.minutes do
    password_salt&.last(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in to do that" unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :set_user_by_token, only: [:edit, :update]

  def new
  end

  def create
    if (user = User.find_by(email: params[:email]))
      PasswordMailer.with(
        user: user,
        token: user.generate_token_for(:password_reset)
      ).password_reset.deliver_later
    end

    redirect_to root_path, notice: "Check your email to reset your password."
  end

  def edit
  end

  def update
    if @user.update(password_params)
      redirect_to new_session_path, notice: "Your password has been updated, please log in."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user_by_token
    @user = User.find_by_token_for(:password_reset, params[:token])
    redirect_to new_password_reset_path, alert: "Invalid token, please try again." unless @user.present?
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    if current_user.update(password_params)
      redirect_to edit_password_path, notice: "Your password has been updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation, :password_challenge).with_defaults(password_challenge: "")
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)
    if @user.save
      login @user
      redirect_to root_path, notice: "You have successfully registered."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if (user = User.authenticate_by(email: params[:email], password: params[:password]))
      login user
      redirect_to root_path, notice: "You have been logged in successfully."
    else
      flash[:alert] = "Invalid email or password."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: "You have been logged out successfully."
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vanderlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div>
      <%= notice %>
      <%= alert %>
    </div>
    <nav class="navbar">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          <p class="title">Vanderlist</p>
        </a>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if user_signed_in? %>
              <%= link_to "Edit Password", edit_password_path, class: "button is-light" %>
              <%= button_to "Log out", session_path, method: :delete, class: "button is-danger" %>
            <% else %>
              <%= link_to "Sign Up", new_registration_path, class: "button is-link" %>
              <%= link_to "Log in", new_session_path, class: "button is-light" %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<section class="section">
  <h1 class="is-size-3">
    <strong>
      Reset Your Password
    </strong>
  </h1>
  <%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
      <div style="color: red">
        <ul>
          <% form.object.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :password, style: "display: block" %>
      <%= form.password_field :password %>
    </div>
    <div>
      <%= form.label :password_confirmation, style: "display: block" %>
      <%= form.password_field :password_confirmation %>
    </div>
    <div>
      <%= form.submit "Reset Your Password" %>
    </div>
  <% end %>
</section>

app/views/password_resets/new.html.erb
<section class="section">
  <h1 class="is-size-3">
    <strong>
      Reset Your Password
    </strong>
  </h1>
  <%= form_with model: @user, url: password_reset_path do |form| %>
    <div>
      <%= form.label :email, style: "display: block" %>
      <%= form.email_field :email %>
    </div>
    <div>
      <%= form.submit "Reset password" %>
    </div>
  <% end %>
</section>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/welcome/index.html.erb
<section class="hero is-medium is-link">
  <div class="hero-body">
    <p class="title">
      Get it done with Vanderlist
    </p>
    <p class="subtitle">
      A simple todo list app
    </p>
  </div>
</section>